import type { NodeState, WorldState } from "@breachverse/domain";

function node(input: Partial<NodeState> & Pick<NodeState, "id" | "name" | "kind" | "position">): NodeState {
  return {
    platform: "Appliance OS",
    services: [],
    vulnerability: 0.35,
    patchLevel: 70,
    edrCoverage: 60,
    detectionSensitivity: 50,
    monitoring: 0,
    compromised: false,
    accessLevel: "NONE",
    isolated: false,
    containsProtectedData: false,
    ...input,
  };
}

export function createInitialWorld(): WorldState {
  const nodes: Record<string, NodeState> = {
    INTERNET: node({
      id: "INTERNET",
      name: "Public Internet",
      kind: "INTERNET",
      platform: "External",
      vulnerability: 0,
      patchLevel: 100,
      edrCoverage: 0,
      detectionSensitivity: 0,
      position: { x: 450, y: 55 },
    }),
    "EDGE-FW01": node({
      id: "EDGE-FW01",
      name: "Edge Firewall",
      kind: "FIREWALL",
      platform: "Fortified Network OS 7.4",
      services: [
        { id: "edge-https", name: "HTTPS Admin", port: 443, exposed: true, vulnerable: true },
        { id: "edge-vpn", name: "Remote Access VPN", port: 8443, exposed: true, vulnerable: true },
      ],
      vulnerability: 0.72,
      patchLevel: 61,
      edrCoverage: 25,
      detectionSensitivity: 45,
      position: { x: 450, y: 150 },
    }),
    "CORP-SW01": node({
      id: "CORP-SW01",
      name: "Corporate Core",
      kind: "SWITCH",
      platform: "Campus Switching OS",
      services: [{ id: "switch-ssh", name: "SSH", port: 22, exposed: false, vulnerable: false }],
      vulnerability: 0.38,
      patchLevel: 82,
      edrCoverage: 10,
      detectionSensitivity: 35,
      position: { x: 450, y: 250 },
    }),
    DC01: node({
      id: "DC01",
      name: "Domain Controller",
      kind: "DOMAIN_CONTROLLER",
      platform: "Windows Server 2025",
      services: [
        { id: "dc-kerberos", name: "Kerberos", port: 88, exposed: false, vulnerable: false },
        { id: "dc-ldap", name: "LDAP", port: 389, exposed: false, vulnerable: true },
        { id: "dc-smb", name: "SMB", port: 445, exposed: false, vulnerable: false },
      ],
      vulnerability: 0.42,
      patchLevel: 79,
      edrCoverage: 92,
      detectionSensitivity: 78,
      position: { x: 130, y: 385 },
    }),
    FILE01: node({
      id: "FILE01",
      name: "Finance File Server",
      kind: "SERVER",
      platform: "Windows Server 2022",
      services: [
        { id: "file-smb", name: "SMB", port: 445, exposed: false, vulnerable: true },
        { id: "file-winrm", name: "WinRM", port: 5985, exposed: false, vulnerable: false },
      ],
      vulnerability: 0.68,
      patchLevel: 58,
      edrCoverage: 84,
      detectionSensitivity: 72,
      containsProtectedData: true,
      position: { x: 290, y: 385 },
    }),
    WS01: node({
      id: "WS01",
      name: "Finance Workstation",
      kind: "WORKSTATION",
      platform: "Windows 11 Enterprise",
      services: [{ id: "ws01-smb", name: "SMB", port: 445, exposed: false, vulnerable: true }],
      vulnerability: 0.64,
      patchLevel: 62,
      edrCoverage: 73,
      detectionSensitivity: 58,
      position: { x: 450, y: 385 },
    }),
    WS02: node({
      id: "WS02",
      name: "Help Desk Workstation",
      kind: "WORKSTATION",
      platform: "Windows 11 Enterprise",
      services: [{ id: "ws02-rdp", name: "RDP", port: 3389, exposed: false, vulnerable: true }],
      vulnerability: 0.58,
      patchLevel: 69,
      edrCoverage: 80,
      detectionSensitivity: 62,
      position: { x: 610, y: 385 },
    }),
    WS03: node({
      id: "WS03",
      name: "Admin Workstation",
      kind: "WORKSTATION",
      platform: "Windows 11 Privileged Access",
      services: [{ id: "ws03-winrm", name: "WinRM", port: 5985, exposed: false, vulnerable: false }],
      vulnerability: 0.31,
      patchLevel: 91,
      edrCoverage: 95,
      detectionSensitivity: 85,
      position: { x: 770, y: 385 },
    }),
  };

  return {
    nodes,
    edges: [
      { id: "E1", from: "INTERNET", to: "EDGE-FW01" },
      { id: "E2", from: "EDGE-FW01", to: "CORP-SW01" },
      { id: "E3", from: "CORP-SW01", to: "DC01" },
      { id: "E4", from: "CORP-SW01", to: "FILE01" },
      { id: "E5", from: "CORP-SW01", to: "WS01" },
      { id: "E6", from: "CORP-SW01", to: "WS02" },
      { id: "E7", from: "CORP-SW01", to: "WS03" },
    ],
    identities: {
      ALICE: { id: "ALICE", name: "Alice", department: "Finance", privilege: "USER", nodeIds: ["WS01", "FILE01"], enabled: true },
      BOB: { id: "BOB", name: "Bob", department: "IT Help Desk", privilege: "HELP_DESK", nodeIds: ["WS02", "DC01", "FILE01"], enabled: true },
      CAROL: { id: "CAROL", name: "Carol", department: "Administration", privilege: "ADMIN", nodeIds: ["WS03", "DC01", "FILE01"], enabled: true },
    },
    credentials: {
      "CRED-ALICE": { id: "CRED-ALICE", identityId: "ALICE", nodeIds: ["WS01", "FILE01"], active: true },
      "CRED-BOB": { id: "CRED-BOB", identityId: "BOB", nodeIds: ["WS02", "DC01", "FILE01"], active: true },
      "CRED-CAROL": { id: "CRED-CAROL", identityId: "CAROL", nodeIds: ["WS03", "DC01", "FILE01"], active: true },
    },
    red: {
      discoveredNodeIds: ["INTERNET", "EDGE-FW01"],
      scannedNodeIds: [],
      footholdNodeIds: [],
      credentialIds: [],
      exfiltrated: false,
    },
    blue: {
      investigatedNodeIds: [],
      identifiedFootholdNodeIds: [],
      intrusionIdentified: false,
      containmentOccurred: false,
    },
  };
}
